### ISSUE TITLE
Camera Controls

### ISSUE THREAD

**Issue by kzap** [moeiscool/Shinobi#10]
would this have any support for camera controls or those are only native to the webserver/ mobile app that came with camera?

i have one that has a http interface which controls the camera and then one uses a mobile app to control the camera... 

isnt there some standard to PTZ camera controls for all these china made devices?

**Comment by moeiscool** [comment]
i have been looking into adding camera controls it doesn't seem difficult for foscams, they also uses a series of different HTTP. (they are the only PTZ i have to test with at this time)... but if you give me your camera model i can try and make some code for it and the foscam... to sort of start a universal method of controlling cameras.

**Comment by moeiscool** [comment]
newest commit now has control options. please check it out.

it works with my foscam.

**Comment by moeiscool** [comment]
here is a video of using foscam control URLs in Shinobi. You can skip half way to see the input settings.
https://www.youtube.com/watch?v=zjs-8LZDc1I

**Comment by kzap** [comment]
Thanks,i have one that has http controls. Ill see if i can implement

On Dec 31, 2016 11:44 AM, "Moe" <notifications@github.com> wrote:

here is a video of using foscam control URLs in Shinobi. You can skip half
way to see the input settings.
https://www.youtube.com/watch?v=zjs-8LZDc1I

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/moeiscool/Shinobi/issues/10#issuecomment-269847276>,
or mute
the thread

**Comment by moeiscool** [comment]
hey just noticed a bug in the code, please download the newest commit or the camera control wont work.
