### ISSUE TITLE
Shinobi Docs Ubuntu Easy Way Documentation

### ISSUE THREAD

**Issue by clessley** [moeiscool/Shinobi#100]
Docs need some tweaking:

Modify INSTALL/ubuntu.sh with `a+x` command (not just -x) and properly state how to execute it validly, ie, `sudo /home/USER/shinobi/INSTALL/ubuntu.sh`.

**Comment by moeiscool** [comment]
`chmod +x` is the same as `chmod a+x`.

Just before that step it says you must be inside the Shinobi directory. Where the `INSTALL` folder is located.
