### ISSUE TITLE
cannot login after fresh install?

### ISSUE THREAD

**Issue by clessley** [moeiscool/Shinobi#101]
logging into shinobi at localhost:8080 fails, the page blinks but does not login to camera control

I am using `ccio@m03.ca` and `password`. Using my own email/pw via config also exhibits the same behavior. In the past the former was the way to gain access to admin to set up person login credentials.

Ubuntu MATE 16.04 x86 via virtual box on Windows 7.

**Comment by moeiscool** [comment]
did you set up `conf.json` with your SQL details? Please check `pm2 logs` to see if there are any errors.

Did you add the file `sql/default_data.sql` in the sql table?

In the near future the install process will ask what credentials you want to use.

**Comment by clessley** [comment]
Conf.json is set up with SQL credentials yes.

I have one row in users, majesticflame as expected and I have the ccio table too. The user.sql import fails, so I manually added a user via adminer but same blinking login after restart. 

Here are pm2 logs -err:

![untitled](https://cloud.githubusercontent.com/assets/12699698/24160079/2e4ac55c-0e1e-11e7-91fe-c2217d76ad94.png)

Perhaps I should purge and reinstall fresh, again? It was so easy the first time.

**Comment by clessley** [comment]
Purged mysql server, purge shinobi folder, re-install "the ubuntu easy way" and then did the all of the "ubuntu harder way" sql commands, restart mysql, delete exiting conf.json, rename conf.example.json to conf.json = login ok with Bunny cams.

**Comment by moeiscool** [comment]
it looks like you are missing dependencies. hmmmm. I guess the installer didn't work correctly for your system.

The solution would have been to run `npm install` sorry about that.

**Comment by clessley** [comment]
The first time i downloaded from guthub clone via browser, the second time strictly through the command line.
-- 
Sent from my mobile device. Please excuse my brevity.
