### ISSUE TITLE
forum location for better collaboration

### ISSUE THREAD

**Issue by kevinGodell** [moeiscool/Shinobi#12]
I would like to suggest nabble for a free forum. We use it for our apache flex project. It seems to work very well as a simplistic place to post via the website, or post via email. Also, everytime there is a commit to our git repo, we get that message posted on the forum. But where ever you decide, it would be better than submitting issues on github.

**Comment by moeiscool** [comment]
http://shinobicctv.freeforums.net/ Ill put it in the readme and wiki that questions and discussion go there.

**Comment by moeiscool** [comment]
Please post on reddit, not freeforums.

https://www.reddit.com/r/ShinobiCCTV/
