### ISSUE TITLE
Docker: Cant change superuser password

### ISSUE THREAD

**Issue by mic159** [moeiscool/Shinobi#130]
Hi there,

I ran Shinobi with docker using the provided image: https://hub.docker.com/r/shinobicctv/shinobi/
And checked over the documentation over here: http://shinobi.video/docs/start, but I cant see how you can change the superuser password when using docker.

If I try to use `docker run shinobicctv/shinobi bash`, it starts PM2 straight away, no shell, so I cannot edit the config file to change the password.

How can I change the superuser password when using the docker image?

**Comment by moeiscool** [comment]
if you are using kitematic then you can click "Exec" and it will bring up terminal for the docker image. Once there you can navigate to the shinobi directory. i think its `/opt/shinobi`. you should then be able to edit super.json. If not then you can always mount `/opt/shinobi` and edit it from there.

Once edited you will have to restart camera.js with `pm2 restart camera.js`
