### ISSUE TITLE
Password reset docs

### ISSUE THREAD

**Issue by Whytehorse** [moeiscool/Shinobi#134]
It would be great if there was documentation on how to reset the password if you forget or lose it. Perhaps just a simple one-line mysql command or some such. Add it to the installation docs maybe or troubleshooting or FAQ?

**Comment by moeiscool** [comment]
I guess didn't really make it clear but there is a way to change passwords for accounts.

On recent versions there is a Superuser panel. A fourth choice on the login screen.

You can read more about how to use it here. http://shinobi.video/docs/start#account-section

I'll elaborate some more about it in the docs in the coming days.
