### ISSUE TITLE
Add raspberry pi to tested cameras

### ISSUE THREAD

**Issue by Whytehorse** [moeiscool/Shinobi#136]
IT WORKS!!!! It's ALIVE!!!! Muahahaha. Tested raspberry pi camera. The rpi command to send video is 
`LD_PRELOAD='' cvlc v4l2:///dev/video0 --v4l2-width 1280 --v4l2-height 720 --v4l2-chroma h264 --sout '#rtp{sdp=rtsp://:8554/}' `

And the settings on shinobi are:
![screenshot from 2017-05-11 18-37-20](https://cloud.githubusercontent.com/assets/121006/25978738/fd5147d6-3678-11e7-91cb-1f3d35eeafee.png)
![screenshot from 2017-05-11 18-38-32](https://cloud.githubusercontent.com/assets/121006/25978749/100aec9c-3679-11e7-871a-93be53af1fbf.png)

**Comment by moeiscool** [comment]
woah nelly. If you could please hit Export then post the file here that would be sweet. Then i can make references here so it also gives credit to the tester :smile:

**Comment by Whytehorse** [comment]
I can't upload a json file so it's tarred and gzipped.
[Shinobi_CZOfp5pwqb_config.json.tar.gz](https://github.com/moeiscool/Shinobi/files/994883/Shinobi_CZOfp5pwqb_config.json.tar.gz)
