### ISSUE TITLE
UI Not showing video recordings older than 17 hours

### ISSUE THREAD

**Issue by ToroNZ** [moeiscool/Shinobi#138]
I've set to keep recordings for 14 days:
![shinobi_videosettings](https://cloud.githubusercontent.com/assets/8522935/25982556/99082592-3731-11e7-9c21-327dc39b2e76.png)

Files are being saved as expected:
![weekoldfiles](https://cloud.githubusercontent.com/assets/8522935/25982568/aeba3eac-3731-11e7-8044-eaede63d031c.png)

But when I click on the camera video history-gram oldest shows:
![oldestvideoui](https://cloud.githubusercontent.com/assets/8522935/25982592/e0acc24a-3731-11e7-8e3c-4d350399b990.png)

I've checked for deletions on the camera.js logs and nothing looks to be deleted:
![screenshot from 2017-05-12 16-46-26](https://cloud.githubusercontent.com/assets/8522935/25982673/912b28fa-3732-11e7-86cd-46b58bd92272.png)

DB records look fine:
![videosindb](https://cloud.githubusercontent.com/assets/8522935/25982852/10b34c14-3734-11e7-852a-35a1dc6ce271.png)

**Comment by moeiscool** [comment]
did this start happening after a recent update?

you have 6 db records but only 2 show in the dashboard? are you seeing records when they first are made and they just gone upon later review? like after you've logged out and logged in?

Could you check your filters?

also that reminds me you can force the cron to rerun and we can know for sure if its deleting stuff.
clear the logs
`pm2 flush`
restart cron and open logs to see what it does.
`pm2 restart cron.js && pm2 logs`

**Comment by moeiscool** [comment]
also please try setting a wide date range on the table. I found myself running in circles once forgetting i had the date range thing :sweat_smile:

**Comment by ToroNZ** [comment]
No, I've set this up a week ago (haven't touched it since).

I have 1050 DB records for HIK1.
I have 1050 mp4 files for HIK1 in the filesystem.
I've selected a wide range (screenshot shows from 5th of May till 12th of May).

Cron.js restarts every hour (had issues with it not cycling properly). Cron looks to be running and doing it's job.

My suspicion is that the javascript code that queries the DB is getting truncated or not passing the date properly. 

Here's what happens on the UI side, it just won't show anything beyond the past 17 hours:
![image](https://cloud.githubusercontent.com/assets/8522935/25986550/8f0399b0-3744-11e7-90ac-ed95a8cb777c.png)

**Comment by ToroNZ** [comment]
Is there a way to change the date format? i.e. not US format

**Comment by ToroNZ** [comment]
Sorry, missed your question:

Issue is persistent across login/logout. Records disappear from the UI after 17 hours, but as per the settings they are not being deleted from the DB or the file-system. So it's pretty much cosmetic.

I've got no filters set for ffmpeg, video-wise all looks and works as expected.

**Comment by moeiscool** [comment]
currently there is no way of modifying the format. Can you ensure you are on the latest version of node.js?
`node -v` should give you the version.

When you do an API request for videos, are all videos there? or is the JSON string missing videos.

Can i get remote access to this installation? maybe I can poke around and find what's going on. As it does seem like a cosmetic issue.

**Comment by moeiscool** [comment]
closing this since after you updated from 6.10.2 to 7.10.0 it started behaving correctly.

There is a limit of 100 for rows, and I will be adding pagination soon.
