### ISSUE TITLE
CSS Issues - Oversized window popup

### ISSUE THREAD

**Issue by ToroNZ** [moeiscool/Shinobi#142]
Two screenshots which show what I'm experiencing with the Video List:
Chrome/Epiphany browser:
![image](https://cloud.githubusercontent.com/assets/8522935/25987122/b2689714-3746-11e7-85b8-f0602eb2b1b2.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/8522935/25987130/bbd61646-3746-11e7-9555-75a98058c26a.png)

You just cannot see the bottom of the popup window which makes you double scroll to get there.

**Comment by ToroNZ** [comment]
Also, Chrome/Epiphany won't show delete button

**Comment by ToroNZ** [comment]
Tested on Windows10 and Ubuntu16, consistent behaviour on both platforms.
Something's up with the way Firefox interprets CSS.

**Comment by moeiscool** [comment]
ah i see it on my Firefox, windows 7. My chrome looks fine.

ah it looks like firefox is unable to parse the CSS property `max-height: calc(100% - 200px);`

**Comment by moeiscool** [comment]
added `height:70%` for firefox only
