### ISSUE TITLE
time length in mp4 record doesnt go past 12 seconds

### ISSUE THREAD

**Issue by mrproper** [moeiscool/Shinobi#15]
Prior to the updates over the holidays this would work.
Now with rtsp -> h264 mp4, i get a file that shows me that it only plays for 12 seconds but keeps playing past that to the specified length

Looking at the ffmpeg command its running is as follows:
ffmpeg -loglevel quiet -i rtsp://192.168.0.29:554/Streaming/Channels/1?tcp -stimeout 2000 -r 20 -acodec libfaac -movflags frag_keyframe+empty_moov -vcodec libx264 -s 2048x1536 -use_wallclock_as_timestamps 1 -q:v 1 /data/Shinobi/events/2Df5hBE/driveway1/2016-12-30T20-09-36.mp4 -f image2pipe -vf fps=1 -s 640x480 pipe:1

**Comment by moeiscool** [comment]
ive been looking at this for a day now.. it seems "copy" works for video and audio.. but then you cant use timestamps or the video filter.. so i need to rework how the timestamp works... since "copy" is actually pretty cool.

**Comment by moeiscool** [comment]
newest commit should have the recording length issue resolved. Minus using timestamps for now.. sadly -vf method is not working correctly with libx264/libx265 and copy encoder.
