### ISSUE TITLE
Subsequent API record + time requests issued while recording should be additive

### ISSUE THREAD

**Issue by pashdown** [moeiscool/Shinobi#153]
record/10/min then another record/10/min 2 minutes later, should result in a total recording time of 18 minutes

**Comment by moeiscool** [comment]
next merge from dev will have this.
add query string `reset=1` to the trigger url so like `http://yourtriggerapiurl?reset=1`

**Comment by pashdown** [comment]
It would be nice to move the camera mode into a ? argument.  IE: ?mode=record ?mode=stop ?mode=start.  The Axis cameras utilize this type of argument better than a path addition.
