### ISSUE TITLE
No Protocol Found for Foscam fi8910w 

### ISSUE THREAD

**Issue by xcolsanders** [moeiscool/Shinobi#166]
I have shinobi setup properly. When trying to connect to my IP camera, the documentation specifies to connect like rtsp://username:pwd@IP:port/videoMain.

When I do this, I can see the thumbnail show what my camera should see, but expanding the stream throws errors from ffmpeg saying "Protocol not found".

Is there anything I can do to try to fix this?

**Comment by moeiscool** [comment]
just chiming in case the close button was hit by accident, did you get it going?

**Comment by xcolsanders** [comment]
Yep, all set. Thanks
