### ISSUE TITLE
Camera Support

### ISSUE THREAD

**Issue by airsoftsoldrecn9** [moeiscool/Shinobi#181]
Just noting an additional camera which can be added to the supported camera list.

Camera Manufacturer: Sunba
Camera Model: 507-20XB
Resolution: 1080P,  2.0 MP
Data Type: MPEG4, JPEG, H.264
Stream URL: rtsp://<IP_ADDR>:554/user=admin_password=zGqJXI8u_channel=1_stream=0.sdp?real_stream  (may need to verify password)
Save To:  WebM, MP4
Notes: Onvif PTZ control through Shinobi not yet functional for this camera.

**Comment by moeiscool** [comment]
Sweet thx! For future posts you can just share them with me on discord :)
