### ISSUE TITLE
Unable to login to Shinobi for the first time.

### ISSUE THREAD

**Issue by svaguilarv** [moeiscool/Shinobi#182]
Hi,

This is the first install I've done with Shinobi which I installed on a Ubuntu Server 16.04 machine.

Everything seems to be running  well except when I try to login for the first time 
![newpicture087](https://cloud.githubusercontent.com/assets/26338645/26801455/ece6257e-4a0a-11e7-9807-72be62e5f113.jpg)

When I try to login with the default login:
Username : ccio@m03.ca
Password : password

Nothing Happens.

But when I try the super User it does login into the SuperUser mode but when i try to add a new user it takes me back to the login page without any error as below.

![newpicture080](https://cloud.githubusercontent.com/assets/26338645/26801556/3ac22752-4a0b-11e7-88ec-f6c693855cf3.jpg)

![newpicture081](https://cloud.githubusercontent.com/assets/26338645/26801571/4368d3e2-4a0b-11e7-975c-9a45e39b9bd4.jpg)

![newpicture082](https://cloud.githubusercontent.com/assets/26338645/26801580/493cadb6-4a0b-11e7-953a-4e7803ae9d5d.jpg)

When I try to login with the new user it returns me to the login page

![newpicture084](https://cloud.githubusercontent.com/assets/26338645/26801604/559fccb4-4a0b-11e7-9978-17707584201a.jpg)

![newpicture086](https://cloud.githubusercontent.com/assets/26338645/26801613/5c84c692-4a0b-11e7-9c4e-b506eabff69c.jpg)

Any Help with this Issue?

**Comment by moeiscool** [comment]
few questions:
1. what method did you use to install?
2. can you get into your sql via command line or some other tool?
2a. if you can get in please check if you have the tables set up. 
 - `framework.sql` - the table structure for the program, no rows are added.
 -  `user.sql` - the user that the conf.json uses to login to the SQL server.
 - `default_data.sql` - **OPTIONAL** this has a demo camera and the user you are trying to login with `ccio@m03.ca`

The issue with your superuser login is that it is unable to get data from the server. Which leads me to believe your SQL tables aren't set up.

The easiest way to set up sql files is to go to shinobi directory then `./sql`. Login to mysql command line like this.
```
mysql -u root -p
```

Once there you can run 
```
source framework.sql
source user.sql
source default_data.sql
```

**Comment by svaguilarv** [comment]
1. I installed it using the easy way

2.- cannot get into the login using ccio@m03.ca 


I can get into SQL
![newpicture088](https://cloud.githubusercontent.com/assets/26338645/26803598/c1eade02-4a12-11e7-96df-aba5f2baff5d.jpg)

![newpicture090](https://cloud.githubusercontent.com/assets/26338645/26803959/43108bb6-4a14-11e7-9575-ba041256b1ef.jpg)

After 
pm2 flush
pm2 restart camera.js
pm2 logs

I get this now:

![newpicture091](https://cloud.githubusercontent.com/assets/26338645/26804127/e3165b5e-4a14-11e7-93c3-a1140415bd0a.jpg)

:'(

**Comment by moeiscool** [comment]
go to shinobi directory.

`Process camera.js not found` because its not already posted to the list you got in the image there.
`pm2 start camera.js` to start it.

you must be inside the main shinobi directory for `pm2 [SOMETHING] camera.js` to work or you will get a similar error to the one you have shown in the image above.

**Comment by moeiscool** [comment]
once shinobi is started please post your logs as well. you can get the logs by doing `pm2 logs`

**Comment by svaguilarv** [comment]
This is what i get after rebooting the machine:

I also tried what you just posted:

![newpicture093](https://cloud.githubusercontent.com/assets/26338645/26805215/ec69bdc8-4a18-11e7-80e3-82fc3a427919.jpg)

**Comment by moeiscool** [comment]
You are not in the shinobi directory, that's why it says `Script not found`. You are in your home directory. Please join me on discord, i can help you better there. http://discordapp.com/invite/mdhmvuH/ As this is general support, i don't want to keep blasting everyone's email boxes. Thanks :)
