### ISSUE TITLE
Username & Password unable to be accepted by NEO Coolcam NIP-31

### ISSUE THREAD

**Issue by 2SI3NX** [moeiscool/Shinobi#184]
Ive tried all the links you sent me in my browser and the few that do work, i enter in my username and password and then it keeps asking me as if its wrong, but its not.

this link: /videostream.cgi?usr=[USERNAME]&pwd=[PASSWORD]

Should the password fields in Shinobi also be filled in? when i fill those in and when i put the path above, then in the probe it says unauthorized. 

Please can you help as to how to set this up?  would really appreciate it.

**Comment by moeiscool** [comment]
you can try an out the username and password in the host field like this
user:pass@cameraURL/video.cgi

To see how a camera is setup you can watch this video https://www.youtube.com/watch?v=G-Zpxu2aEHg it also has a link to a demo monitor you can import.

Also the issues section is for bugs only, not general support.
