### ISSUE TITLE
Default login email/password listed do not work with fresh install

### ISSUE THREAD

**Issue by Zerqz** [moeiscool/Shinobi#191]
Using email: "ccio@m03.ca"
password: "password"

at the login page of a fresh install does not proceed, and the page just refreshes.

**Comment by SudarshanSudie** [comment]
@Zerqz issue exists , unable to login after fresh install . Any idea ?

**Comment by Qasimmodo** [comment]
@SudarshanSudie Are you sure this is a issue with the software itself, I suggest you come to our support discord for assistance. We'll be more than happy to help. https://discord.gg/yuRsEUZ

**Comment by moeiscool** [comment]
Thank you @Qasimmodo :) . @SudarshanSudie Please find us over in the community chat. http://discordapp.com/invite/mdhmvuH/ We can better help you there.
