### ISSUE TITLE
Lack of good support for vendor features

### ISSUE THREAD

**Issue by pimlie** [moeiscool/Shinobi#207]
Yesterday I was giving Shinobi a try but I believe that at the moments its lacking good support for different vendors. E.g. the issue I mentioned yesterday on discord was with PTZ control, it seems at the moment you can only enter urls for a GET request to control a camera. But e.g. Hikvision camera's require a PUT request with xml data to their [ISAPI](http://oversea-download.hikvision.com/uploadfile/Leaflet/ISAPI/HIKVISION%20ISAPI_2.0-IPMD%20Service.pdf). A lot of vendor's also support PRESET's or automatic patrol movements, afaik these functionalities are not supported atm. 

To fully support all different vendors there should be a feature abstraction layer so you can easily add features for different vendors, whatever their implementation. [Here](https://forums.zoneminder.com/viewtopic.php?t=25442) you can find an example of a ZoneMinder control script for Hikvision PTZ movement.

As plugins are runing as separate processes, I would think that implementing plugins for this would be a bit costly. Unfortunately my knowledge of the inner workings of Shinobi are not extensive enough to propose a good solution at the moment. Let me know what you think :)

**Comment by moeiscool** [comment]
Sorry I didn't see your message in the board, you can leave me a PM if you need me to see something in specific.

You can post suggestions in the suggestions channel in the discord community chat. The issues section is only for bugs. Please do not post questions or suggestions in the Issues section.

I don't actually have any cameras like this to test with so I can't put it together myself without wasting a lot of effort. If you want you can either donate hardware that does this or make a pull request with the options. I can look it over and do remote testing with your stuff.

do you have any examples in node.js? I don't really like reading zm code as its usually just so poorly written I end up wasting way too much effort just trying to figure out how it works. You could create a node.js version of it and I could possibly integrate it.
