### ISSUE TITLE
ffmpeg processes keep running after sign out

### ISSUE THREAD

**Issue by pimlie** [moeiscool/Shinobi#208]
I have added 3 camera's in 'Watch-only' mode to my Shinobi setup based on the `shinobicctv/shinobi` docker image. When I start the docker container all is well, when I sign in all is well too but if I then sign out the ffmpeg processes keep running for those 3 camera's. Only until I shutdown the docker container the ffmpeg processes are stopped (duh). 

As all 3 ffmpeg processes are running at 20-40%, it's quite a bit of overhead while nobody is watching the camera's..

**Comment by moeiscool** [comment]
its supposed to. It's not like ZM where it opens a new process for each client and for each task. It uses the single FFMPEG process to pretty much do everything (alongside the node app).

If you want to kill the processes you have to set them to Disabled.
