### ISSUE TITLE
Power Video Viewer: Date Range dialog: Dropdowns for hour, minute and AM/PM not opening

### ISSUE THREAD

**Issue by DL44227** [moeiscool/Shinobi#209]
Hello,

In the Power Video Viewer choosing a range with the Date Range dialog, it is not possible to select hours, minutes and AM/PM from dropdown elements (hourselect, minuteselect, ampmselect), because they don't open in Firefox. In Chromium they are working as expected.

Environment: Firefox 53.0 (64 Bit), Linux Mint

**Comment by moeiscool** [comment]
could you please post your console log output, it should have some stuff in red.

**Comment by DL44227** [comment]
It says: "Loading of mixed active content "http://my.domain:8080/libs/js/jquery.min.js" was blocked. My server is reachable via https://my.domain/... (apache reverse proxy). So maybe there are absolute http references in the code?

**Comment by moeiscool** [comment]
```
<script src="/libs/js/jquery.min.js"></script>
```

this is how i define jquery.

Can you post everything? You should be able to click a little arrow next to the error for it to show more details. please do that to all the errors and post.

**Comment by DL44227** [comment]
Please find a screenshot below
![mixedcontent](https://user-images.githubusercontent.com/28777966/27655076-6482e1e4-5c44-11e7-989f-c90cb9eef32a.jpg)

**Comment by andersonls** [comment]
Same issue here, using Firefox 54.0 (64-bit) with Linux Mint. The Shinobi, however, is running on docker with the image shinobicctv/shinobi.

The problem occurs within any of the Calendar, Timeline and Videos List. The XML Parsing error pops up when opening any of the mentioned windows while the Reference Error only pops up in the Timeline window.

I also noticed that the dropdown "flashed" when clicked (it opens but quickly closes).

![screenshot](https://user-images.githubusercontent.com/1561038/27701911-bc19e81e-5cd8-11e7-8d6a-4127f31ce162.png)

**Comment by DL44227** [comment]
I have tried nginx based reverse proxy. Still the same issue, mixed content. So I assume it is not an apache2 related issue.

**Comment by moeiscool** [comment]
Please try the latest master

**Comment by DL44227** [comment]
No change in the latest dev. Still the same issue.

**Comment by DL44227** [comment]
Probably I found a hotfix for this, please see https://github.com/moeiscool/Shinobi/pull/236
