### ISSUE TITLE
Creating a region on one cam overwrites all regions of other cams

### ISSUE THREAD

**Issue by DL44227** [moeiscool/Shinobi#214]
I have defined a region (name "red") for one cam. It is something special because it excludes some areas of this cam. After saving and opening the region editor of an another cam, I found the same region there. It seems that the region editor doesn't load the correct region of particular cam. Instead it loads the region of the cam, where the region was last defined.

**Comment by moeiscool** [comment]
ah i think i know what happened. It set it to load nothing if no regions were found. So it didn't release the old region from the previous monitor (in the client side). If you have at least one region per cam this shouldn't happen. I will add a fix for this, thanks :D

**Comment by DL44227** [comment]
After updating to the last dev, this issue disappeared.
