### ISSUE TITLE
Power Video Viewer displays only motion events for last one hour

### ISSUE THREAD

**Issue by DL44227** [moeiscool/Shinobi#215]
I found, that the Power Video Viewer is not displaying motion events in the timeline which are older than one hour. This seems to be a bug because the events are in the database though (please see the screenshots).

**Comment by DL44227** [comment]
![powerviewer_err01](https://user-images.githubusercontent.com/28777966/27873759-8666cbae-61ad-11e7-89c8-18150b267b2c.png)
![powerviewer_err02](https://user-images.githubusercontent.com/28777966/27873766-89deb058-61ad-11e7-8897-b7b7d23b4e40.png)

**Comment by moeiscool** [comment]
your limit of events is set to 500 you can make it a larger number to see more events
