### ISSUE TITLE
Gui Bug

### ISSUE THREAD

**Issue by leeyuentuen** [moeiscool/Shinobi#224]
![selection_049](https://user-images.githubusercontent.com/1487966/27989112-e11b67c2-6431-11e7-89a2-12709c9dd088.png)
The calculation of the disk space is not correct.
I have mount a nfs folder for storage the video, it is about a few TB but it only count the storage on the VM disk of 15GB.

**Comment by moeiscool** [comment]
click your username in the top left > Settings
then change Max Storage Amount to whatever you want.
