### ISSUE TITLE
Don't see a record section in monitor setting

### ISSUE THREAD

**Issue by sguilly** [moeiscool/Shinobi#227]
Hi,

I have the same #203 issue.

When i start a record :
0|camera   | uncaughtException { Error: read ECONNRESET
0|camera   |     at exports._errnoException (util.js:1022:11)
0|camera   |     at Pipe.onread (net.js:569:26) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

I want to try a other output format but I don't see a record section in monitor setting (as describe in the documentation).

I try the ninja way and the docker way and i have the same issue on both.

**Comment by moeiscool** [comment]
set mode to record and the field will appear.
that error usually means ffmpeg is dead, didn't start, or is still starting. check you have ffmpeg 3.x installed.
