### ISSUE TITLE
FFMPEG hogs CPU and Ram

### ISSUE THREAD

**Issue by Whytehorse** [moeiscool/Shinobi#234]
I have 14 cameras I want to record to disk. After pointing Shinobi to about 4 cameras it overloads the server. It looks like ffmpeg is responsible. How do I use the ffmpeg options and shinobi to tell it to use my gpu and not transcode every stream, just dump to disk and make low framerate monitors?

**Comment by moeiscool** [comment]
Please forward general questions to Discord.

**Comment by Whytehorse** [comment]
who is discord?
