### ISSUE TITLE
Doubling file extension (ENOENT in camera.js)

### ISSUE THREAD

**Issue by DL44227** [moeiscool/Shinobi#245]
I found the following error message in the camera.js log. This message is logged sometimes on start of camera.js.

`2017-07-24T12:45:03+02:00 { Error: ENOENT: no such file or directory, stat '/opt/shinobi-dev-20170720/videos/xxx/yyy/2017-07-24T12-39-59.mp4.mp4'
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/opt/shinobi-dev-20170720/videos/xxx/yyy/2017-07-24T12-39-59.mp4.mp4' }  
`

It seems, that for some reason the file name extension is doubled (.mp4.mp4). Unfortunately this log output does not reference the line where it has occured.

**Comment by moeiscool** [comment]
Well that is very bad

**Comment by moeiscool** [comment]
i haven't been able to reproduce this, can i get your monitor settings for the camera that this is happening to? or is it happening to all of them?
