### ISSUE TITLE
Duplicating monitors when updating Id

### ISSUE THREAD

**Issue by mattdurant** [moeiscool/Shinobi#258]
Is it intended that changing the monitor ID of a monitor and saving it duplicates the monitor with the new ID and leaves the original as well, or is this a bug?

**Comment by moeiscool** [comment]
that's how it is supposed to be. Just above the fields in the input section it reads : 

> You can duplicate a monitor by modifying the Monitor ID then pressing save. You cannot use the ID of a monitor that already exists or it will save over that monitor's database information.

The issues section is not for general questions, it is only for bugs related to the software. Please ask general questions where appropriate.
