### ISSUE TITLE
Is the new license setup for Shinobi/Pro correct?

### ISSUE THREAD

**Issue by Cozza38** [moeiscool/Shinobi#261]
> The issues section is for bugs with the software, not personal opinions or questions. Discussion must revolve around a bug. I see no code snippets.

**Comment by mattdurant** [comment]
We've covered all of this already, and it's getting ridiculous now.  I regret trying to get involved in this project at all.  Moe, you need to get legal advice on this, all of the changes you are trying to make are against the terms of the license you have been operating under.  I'm sure this is going to be closed without discussion, but at least it'll be here in the record.

**Comment by Cozza38** [comment]
This isn't a "personal opinion or question".

This is an "issue" related to the license of the software. It is as important as the code itself is.

**Comment by moeiscool** [comment]
Choosing to ignore what I say is not acceptable. I am sorry.
