### ISSUE TITLE
application starts then aborts, fresh install Ubuntu 16.04

### ISSUE THREAD

**Issue by the4ndy** [moeiscool/Shinobi#28]
I have a fresh install of 16.04 that I am trying to install Shinobi on. I used the Install.sh script and everything appeared to have worked fine. I run ``` node camera.js ``` and that says its listening on 8080 but then shortly after that (like before i can get to a browser and test it out) I get the following error
```
nodejs: src/unix/linux-core.c:747: read_times: Assertion `num == numcpus' failed.
Aborted
```
Any assistance is greatly appreciated. Thanks

**Comment by moeiscool** [comment]
It seems like a problem with either `os-utils` or `os` (plugin for reading hardware status).

In this version of camera.js i have disabled those functions. Please overwrite your your old camera.js with this one.

https://mega.nz/#!65o3TJAS!nnp6y6GN3rJh5kNTRNrRGP3m6J3IMvQVPkC18oTbDRo

**Comment by moeiscool** [comment]
Have you gotten up and running? I sure hope so. If not join me on Discord I'll be able to give you quicker help :) https://discord.gg/mdhmvuH for now I'll close this thread.

**Comment by paladine-raistlin** [comment]
I have same issue with latest on Ubuntu 16.04 LXC, Proxmox. I tried your modified file and that fixes issue. 
Thank You

**Comment by moeiscool** [comment]
please note that the modified file is very old. please join me on slack so we can work out a better solution.

**Comment by moeiscool** [comment]
@paladine-raistlin and I have found the solution. Updating your node.js to 7.2.0(+) eliminates the issue.

Updating Node.js can be done in the following way
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```
