### ISSUE TITLE
Number of Days to keep Videos - Not working

### ISSUE THREAD

**Issue by vLX42** [moeiscool/Shinobi#35]
The videos are not getting deletede after x days.

I have set it to 3 days, but I now have recording for 6 days

**Comment by moeiscool** [comment]
Do you have `cron.js` running? I really should write something about it lol, sorry about that.

**Comment by vLX42** [comment]
I tried to run cron.js, it deleted all events in the database but non of the files. Maybe something with dateformat or OS. I'm running Ubuntu 16.04.1 LTS and MariaDB (Mysql fork)

**Comment by moeiscool** [comment]
just pushed an update for the cron file.

**Comment by jm93944** [comment]
I had the same problem the videos were removed from Shinobi, but files were not deleted. I just updated and will see if that fixes it.

**Comment by moeiscool** [comment]
I think I'll keep this open until I know cron actually works for everyone, I just closed it because I got no response :(

**Comment by vLX42** [comment]
Still having the same problem. If i can do anything to help please say so.

**Comment by moeiscool** [comment]
Can you join me on slack? We can easily talk about what you're experiencing. I may just rewrite the cron file...

**Comment by moeiscool** [comment]
i have reverted the cron to an older version. currently It will ignore orphaned files. I still need to create a method for this.
