### ISSUE TITLE
Install instructions for native OS X in wiki

### ISSUE THREAD

**Issue by pliablepixels** [moeiscool/Shinobi#55]
(looks like your wiki doesn't allow 3rd party edits, so creating an issue)

While trying to get shinobi installed on OS X,  I found the following wiki issues:

In the native OS X part of the wiki:
1. You have provided an INSTALL.sh script but the wiki doesn't mention using it to install deps. If that is intentional, then:
1.1 pm2 is not part of the default node install - you might want to add a note to install pm2 if not present (needed for UPDATE.sh)
2. The clone instruction says
```
git clone git@github.com:moeiscool/Shinobi.git -o github ./Shinobi`
```
2.1: remove extraneous back-tick at the end
2.2 why are you recommending `-o github` ? `origin` and `upstream` are the typical norms when you fork and contribute
2.3 Similarly, `./Shinobi` is also not necessary

**Comment by moeiscool** [comment]
1. I supposed should mention what it installs in list form. It will only work on ubuntu to get the primary dependencies.
1.1 i don't think i understand correctly. At the end of the INSTALL.sh there is `npm install pm2 -g` this installs pm2 globally. yes i suppose i should note that in the update section :sweat_smile: 
2. its actually my first time using github/git in this way. So i am not familiar with formalities. :sweat: . Another fellow generously did a PR with a bunch of additions and i think this might have been one of them. Probably the result of a long day :smile: Are you able to do PR to the wiki? i noticed there is a clone thing for it when i'm editing it.

is this right?
```
git clone git@github.com:moeiscool/Shinobi.git -o origin
```
