### ISSUE TITLE
monitor video freezes after maximizing.

### ISSUE THREAD

**Issue by ITwrx** [moeiscool/Shinobi#67]
when maximizing the cam stream of either the bottom or bottom right streams, the cam stream that replaces the maximized stream is frozen. top right stream doesn't display this freezing behavior in my somewhat limited testing. a reconnect gets the frozen stream going again.

thanks.

**Comment by moeiscool** [comment]
newest commit is doing this?

**Comment by ITwrx** [comment]
whoops! it works with latest! :)
thanks.

**Comment by moeiscool** [comment]
what chat platforms DO you use? maybe there is a slack addon you can add so you can talk to us on slack too? the error you mentioned was actually brought up 1 or 2 days ago by kevin in slack... and you were there you'd know!  :stuck_out_tongue:
