### ISSUE TITLE
Camera not added on initial add

### ISSUE THREAD

**Issue by tridiumcontrols** [moeiscool/Shinobi#81]
I created an RTSP stream from an IP camera and i clicked the green button to add the camera. After the window closed I did not see my camera added. I ended up refreshing the web page to get it to come up. Any subsequent affected streams work fine and get added and show up automatically. Only happens on an initial camera add. 

Using chrome on a fresh install of Ubuntu 16.04 server x64

**Comment by moeiscool** [comment]
Any logs in pm2? You can check by running in terminal :
pm2 logs
