### ISSUE TITLE
Ubuntu Easy Way Script needs tweaking, fails install. 

### ISSUE THREAD

**Issue by tridiumcontrols** [moeiscool/Shinobi#82]
I had to go between easy way and hard way to determine my Install issueS. 

First, the script asks for the mysql password that I setup in the previous step, I put in the password and I get an error 2 for all .Sql imports. 

Found the issue, I had to manually navigate to sql directory inside shinobi them execute "mysql -u root -p" which asked for my root password, and I entered the "mysql>" prompt, I entered "source user.sql" and did for each database required, framework etc. Which imported successfully, I edited mysql, and wanted to start camera.js

I tried pm2 start camera.js and got an errored status from pm2, checking logs it was missing npm modules. 

I manually downloaded the mega.nz node_modules and stuck it in the shinobi directory where camera.js is, and tried to start camera.js again and found modules that were missing. 

I used npm to install 5 missing modules, don't remember the ones I downloaded, one of then was webdav and etc, that were not included in the downloaded node_modules folder. 

After manually installing the missing NPM modules, then I started camera.js and all worked well from then on. 

Makes it difficult for a new comer to use the easy way script but need to reference the hard way steps to get it working. 

All in all, was easy to figure out, but wanted to point out the challenges I ran during install. 

Solid work moeiscool, takes the crown, cake and all things from zone minder. Awesome project, much needed. Zone minder does not come close to the stability of shinobi, OMG the issues I dealt with zone minder I was quickly steered away, and found this as an alternative. Great work.

**Comment by moeiscool** [comment]
Yowza, I will be able to diagnose the setup files and instructions more easily with this. Thank you :D
