### ISSUE TITLE
montage view won't play more than "six" monitors

### ISSUE THREAD

**Issue by kdsoo** [moeiscool/Shinobi#83]
I registered 16 cameras running with same specification (720P mjpeg)
But cannot preview every monitors simultaneously. It only shows 6 of them properly and black blank video for the rest.
I presume this is caused by the spec of my browser which is by design. According to the google product team's thread, chrome supports upto 6 simultaneous connections from same origin per browser tab https://productforums.google.com/forum/#!topic/chrome/FnQKOXNStic

Is there any tweak to run more than 6 previews at the same time?

**Comment by moeiscool** [comment]
I am guessing you have them set to MJPEG for stream type. By setting this base64 you defeat these limitations. The only real down side is that it takes more processing power from the client computer. Mobile devices might lag a bit if too many streams are open at one time.
