### ISSUE TITLE
Unexpected token ...

### ISSUE THREAD

**Issue by Alko89** [moeiscool/Shinobi#95]
I just went through the harder way installation on Ubuntu and am unable to execute `nodejs camera.js`.
The only error I get is `uncaughtException [SyntaxError: Unexpected token ...]`. 
I have installed Shinobi in a virtual machine a few weeks ago with no problem.

**Comment by Timo-Linde** [comment]
i had the same problem on debian over here i just installed a newer nodejs version

https://nodejs.org/en/download/package-manager/

**Comment by Alko89** [comment]
Thanks! That solved the issue. Strange it seems it works on Ubuntu LTS.

**Comment by clessley** [comment]
No its doesn't, got the same error using it on ubuntu yesterday after upgrade script and clean install.

On March 17, 2017 3:33:16 AM PDT, "Aleš Ferlan" <notifications@github.com> wrote:
>Thanks! That solved the issue. Strange it seems it works on Ubuntu LTS.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/moeiscool/Shinobi/issues/95#issuecomment-287320402

-- 
Sent from my mobile device. Please excuse my brevity.

**Comment by Timo-Linde** [comment]
@clessley Can you please provide `node -v`

**Comment by moeiscool** [comment]
nodejs 7.2.0(+) is required to run Shinobi.

you can update node.js like this if you dont have nvm :
```
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
```

**Comment by Alko89** [comment]
I admit, I don't remember what I did that it worked previously. Maybe I did updated node through npm.
Anyway its working now. Thank you.

**Comment by moeiscool** [comment]
it worked before because the older version of node that you had was capable of running the version of `camera.js` that you had. As low as 4.x would work on older versions. Now it has methods and functions that the older versions are no longer capable of running.

**Comment by clessley** [comment]
@Timo-Linde This was closed before I had a chance to retry the latest version. The latest on Ubuntu MATE 16.04 LTS inside a virtual box on Windows 7 installs ok and the previous error has been fixed.
