### ISSUE TITLE
Layout change is broken monitor

### ISSUE THREAD

**Issue by douglasPinheiro** [moeiscool/Shinobi#96]
Monitor is broken when sidebar is open.

Suggestion to improve, make sidebar absolute, and open over cameras.

Obs: I'm using ubuntu 16.04 with firefox

![screenshot from 2017-03-19 08-58-50](https://cloud.githubusercontent.com/assets/8483126/24080643/9ca62322-0c82-11e7-8029-20d0b3d1dfe4.png)
![screenshot from 2017-03-19 08-58-39](https://cloud.githubusercontent.com/assets/8483126/24080644/9ca83838-0c82-11e7-90b5-91e2eb7fa99f.png)

**Comment by moeiscool** [comment]
I've added a css rule to make them smaller for lower resolutions. The current dev commit has this fix (added today). The next pull request to master will have it.
