### ISSUE TITLE
Fullscreen not working

### ISSUE THREAD

**Issue by douglasPinheiro** [moeiscool/Shinobi#97]
Camera not working only on fullscreen

![screenshot from 2017-03-19 09-07-33](https://cloud.githubusercontent.com/assets/8483126/24080735/a9940d46-0c83-11e7-991a-20b2501da29b.png)
![screenshot from 2017-03-19 09-07-17](https://cloud.githubusercontent.com/assets/8483126/24080734/a993c30e-0c83-11e7-9f1c-95c622278a73.png)

**Comment by moeiscool** [comment]
Base64 has issues fullscreening at this time. If you have less than four cameras running i can suggest using MJPEG or HLS as the Stream Type instead. This will do proper fullscreen.

**Comment by douglasPinheiro** [comment]
I will need use with 16 cameras.
So I will try change the Stream type, to see if works.
Thanks
