### ISSUE TITLE
stops recording after deleting segment

### ISSUE THREAD

**Issue by Timo-Linde** [moeiscool/Shinobi#98]
Shinobi stops recording after deleting one or more segments over the UI from the past. e.g. one hour ago.

Shinobi records the actual segment to the end and then stops.

The UI gives me this error: Cannot save non existant file. Something went wrong.

**Comment by moeiscool** [comment]
Any logs in pm2? Are clocks adjusted for daylight savings? I was having timestamp issue a week ago, I thought I fixed it. Guess not. What OS did you install on? When you refresh does the GUI appear normal?

Deleting any video will halt recording? Or jus the last one?

**Comment by Timo-Linde** [comment]
no logs in pm2.  
OS:  Debian GNU/Linux 8 (64 Bit)

The video remains in the list till i reopen the list.
Deleting any video will halt recording after the segment is finished.

I refreshed the GUI and it appears normal.

**Comment by moeiscool** [comment]
any logs in your browser console when running the command? could you please paste the last few outputs after running the command.
